### ISSUE TITLE
CLHS replacement project coming up in 2023

### ISSUE THREAD

**Issue by Hexstream** [fonol/cl-community-spec#1]
Hello,

Do what you want but I thought I'd let you know about [my CLHS replacement project which is coming up in 2023](https://roadmap.hexstreamsoft.com/#public-domain-spiritual-successor-to-the-clhs).

I don't claim I'm unbiased, but I certainly think I'm by far the one who has the best shot at this.

So probably only work on this if you don't mind the duplication of effort. ;)

**Comment by fonol** [comment]
Hi, 
thanks for the heads-up. I don't see any problem with there being two  efforts! :)
