### ISSUE TITLE
macroexpand-1 incorrect arrow placing

### ISSUE THREAD

**Issue by lockie** [fonol/cl-community-spec#16]
Hi! Looks like the arrow is incorrectly placed for `macroexpand-1` at [macroexpand page](https://cl-community-spec.github.io/pages/macroexpand.html), it should be
* `macroexpand-1 form &optional env ⇒ expansion, expanded-p`, instead of currently present
* `macroexpand-1 ⇒ form &optional env expansion, expanded-p`

P.S. Thanks for the awesome project!

**Comment by fonol** [comment]
Thanks, should be fixed now! :)

**Comment by lockie** [comment]
Awesome, thank you!
