### ISSUE TITLE
Glossary HTML IDs

### ISSUE THREAD

**Issue by olnw** [fonol/cl-community-spec#21]
I think definitions in the glossary should have HTML IDs, so that they can be hyperlinked from other entries in CLCS. That's what the HyperSpec does, and it's quite useful.

`html_in/Glossary.html` has anchors that use the `name` attribute:
```
<a name="index-absolute"></a>
```
But they're not present in `html_out/Glossary.html`. Also, the `name` attribute for the `<a>` tag is [deprecated in HTML5.](https://stackoverflow.com/a/32429250)

I think the correct way to do it is like this, using the `id` attribute instead:
```
<dt id="absolute"><b>absolute</b></dt>
<dd><p><i>adj.</i>
  1. (of a <i>time</i>)
     representing a specific point in time.
  2. (of a <i>pathname</i>)
     representing a specific position in a directory hierarchy.
  See <i>relative</i>.
</p>
</dd>
```

**Comment by fonol** [comment]
That makes sense. I checked the CLHS, and in there, the stuff in the glossary that is within `<i></i>` tags links to  other sections in the glossary. Maybe a way to approach this without getting insane would be to make a script that does sth like
1. Go over `html_in/Glossary.html` and replace the `<a name="..."></a>` with IDs as you proposed.
2. Go over `html_in/Glossary.html` and replace all `<i>...</i>` with a link to the respective section. This might not work in all cases, e.g. if the section ID is "binding" but the tag is `<i>bindings</i>`, but maybe there are ways to be smart about this.
3. Collect all found IDs in the glossary, and then go over all pages in `html_in/` and look for `<i>...</i>` that could be turned into links...

Maybe I'll have a shot at this in the evening (unless you want to do it!).

**Comment by olnw** [comment]
I've made a rudimentary Emacs Lisp script that solves your first point, and creates a new glossary file with the `id` attributes. Your second and third points, I expect, will be quite difficult.
```
;; -*- lexical-binding: t -*-
(with-temp-file "new-glossary.html"
  (insert-file-contents "html_in/Glossary.html")
  (let* ((remove-anchors '("Glossary"
                           "Glossary-2"
                           "index-printer-escaping-2"))
         (ids
          (cl-loop while (ignore-errors (search-forward "<a name=\""))
                   do (mark-sexp)
                   for id = (buffer-substring (point) (mark))

                   do (cond
                       ;; Two <a> tags at the top are not necessary.
                       ;; Remove those.
                       
                       ;; There is also an unnecessary "index-printer-escaping-2",
                       ;; when "index-printer-escaping-1" already exists.
                       ((member id remove-anchors)
                        (kill-whole-line))

                       ;; Section headings. Add the ID to the <h4> tag.
                       ((or (string= id "Non_002dalphabetic")
                            (and (= (length id) 1)
                                 (char-uppercase-p (elt id 0))))
                        (kill-whole-line)
                        (search-forward "<h4 class=\"subheading\"")
                        (insert (format " id=\"%s\"" id)))

                       ;; Everything else. Add the ID to the <dt> tag.
                       (t
                        (kill-whole-line)
                        (search-forward "<dt")
                        (insert (format " id=\"%s\"" id))))

                   collect id)))))
```

**Comment by fonol** [comment]
Nice! I don't have any strong opinion on the "index-" prefix, but why not remove it to save some bytes :-)?
If you are okay with it I can try myself on to do the points 2 and 3! I would do it in Python though since I don't know Emacs Lisp... You could commit the updated Glossary.html and then I could read out the ids.

**Comment by olnw** [comment]
Sure, I'm happy for you to solve those parts, since I'm going to bed soon anyway. I'll open a PR soon.

**Comment by olnw** [comment]
I noticed that, when visiting a glossary term directly, it gets obscured by the search bar; to see it, one must scroll up slightly. I think a visual hint, [as described here](https://stackoverflow.com/questions/11142125/css-highlight-a-div-when-the-id-is-linked-to-using-an-anchor), would be useful. What do you think?

**Comment by fonol** [comment]
I now pushed a version with the links inserted. It was kind of a pain as you predicted, but I think it went okay. There might be manual correction needed in some places though, but from what I saw the majority looks good. I also think this is now a good  time to start working on the HTML pages in `html_out/` directly, instead of always going through the conversion script. Always converting made sense when the navigation on the left, the backlinks and the search terms for the `script.js` changed frequently (because they were all regenerated by the script), but now, I think it will be more convenient to just work on the final HTML directly. 


> I noticed that, when visiting a glossary term directly, it gets obscured by the search bar; to see it, one must scroll up slightly. I think a visual hint, [as described here](https://developer.mozilla.org/en-US/docs/Web/CSS/:target), would be useful. What do you think?

I also noticed, a visual hint is a nice idea!

**Comment by olnw** [comment]
Thanks. I have two questions:

- Does the website update automatically? It seems to be a bit out of date.
- How will backlinks be regenerated without `convert.py`? It could be possible that we find more missing links, and need to regenerate backlinks after adding them.

**Comment by fonol** [comment]
1. I need to trigger a rebuild with a script, it should be up-to-date now!
2. Right, that might happen. I will add a script that goes over the pages and updates the backlinks if necessary.

I found another thing concerning the anchors on glossary.html: https://getpublii.com/blog/one-line-css-solution-to-prevent-anchor-links-from-scrolling-behind-a-sticky-header.html

**Comment by olnw** [comment]
Great — I think all of these changes have significantly improved usability. Now, perhaps the search box should search glossary terms as well?

**Comment by fonol** [comment]
I agree that would be nice.
