### ISSUE TITLE
Table of Contents Missing

### ISSUE THREAD

**Issue by jgarte** [fonol/cl-community-spec#28]
# CLCS

![image](https://github.com/fonol/cl-community-spec/assets/47760695/a5338fbf-0469-496c-8b47-492e5a3af8be)

# CLHS

![image](https://github.com/fonol/cl-community-spec/assets/47760695/8347a164-2334-4210-9c24-0e50fa911470)

WDYT

**Comment by fonol** [comment]
Thanks for the report, fixed with [#a82658d](https://github.com/fonol/cl-community-spec/commit/a82658dfbbd1ed86f4f314c0b1a5fcbb1bc22f3d).
