### ISSUE TITLE
index mapping symbols to html

### ISSUE THREAD

**Issue by russell** [fonol/cl-community-spec#4]
Hi,

Is there an index mapping symbol to html locations, so that we can implement an emacs mode to match the hyperspec one that can be called to describe a symbol?

**Comment by fonol** [comment]
Hi,
there is a big fat blob of all the searchable pages in [scripts.js](https://github.com/fonol/cl-community-spec/blob/main/scripts.js). It is used for the search, and contains a list of all the pages, with the name of the .html file as second item in each pair (with the `.html` stripped).

However, this will be of limited usefulness for now I guess. Many pages do not describe a single function/accessor/macro, but a whole bunch of them. See for example [first.html](https://cl-community-spec.github.io/pages/first.html). The search currently only lists the item that the HTML file is named by. E.g. `first.html` can only be found by typing `first` in the search, not by typing `second` or `third`. This is actually one of my next todo items, to parse all the headers, and extract the other contained functions to fill out missing links and to use them in the search. When I do this, I will think of your use-case and maybe split out a JSON file or something that lists all the pages and their keywords.

**Comment by russell** [comment]
I don't think it matters if there is more than one symbol to a page, using anchors can fix that.  For pages where all the details are combined, it shouldn't matter much.

One case to consider is symbols that are described on multiple pages. Then it would be good to provide disambiguating index pages. So if the symbol is a function and a type, and they are detailed on different pages, having an index that offers a choice, would be helpful when linking from external tools like Emacs.

regarding search i don't know how much research you have done so far.  I am no expert but there are 2 project i know of that have static search and they do it very differently

* the sphinx project has pretty good static search https://github.com/sphinx-doc/sphinx/blob/a1c10f5d5e9734c6722d04b0b0781a5d88860745/sphinx/themes/basic/static/searchtools.js it's used here https://www.sphinx-doc.org/en/master/search.html?q=functions and it seems to be based on some stemming algorithm https://github.com/snowballstem/snowball but this isn't an area of expertise for me.  I would just try and use someone elses search tooling because search is hard.... 
* mkdocs also has search, but it's implemented by shipping the entire contents of each page as part of a large json blob, that is searched in the browser.

shipping a large json blob might sound like cheating, but if it gets you search faster, i think it would be worth it, it's not uncommon for blobs of JS to be quite large these days, and if it doesn't change much, local caching will help.

if you can provide a json based symbol index though that will do it, then that can be pulled into emacs and processed there

**Comment by fonol** [comment]
With eca79872c956dadea6c05afd9632255520737bd6, the different keywords from the page header are now added to the searchable keywords. You can find a list of all the searchable items in [searchable_terms.json](https://github.com/fonol/cl-community-spec/blob/main/searchable_terms.json). No distinction between different types of symbols yet though. 

Concerning the search, thanks for your links, but actually, I don't plan to add any 3rd party dependency just for that. I am actually quite okay with how the current search works. Right now, it's just 80 lines of plain JS (excluding the large "index" of searchable pages of course), and it get's the job done reasonably well. Sure there is no fuzziness to it, but I can live with that.
