### ISSUE TITLE
multiple-value-prog1

### ISSUE THREAD

**Issue by charJe** [fonol/cl-community-spec#6]
I love this project. 

This page is looking a little funny
https://cl-community-spec.github.io/pages/multiple_002dvalue_002dprog1.html

`multiple-value-prog` 1 ⇒ first-form {form}*

**Comment by fonol** [comment]
Hi, thanks for the report. Fixed with 9d0052e73ce21ef5ea3c54a53a5fe3b7aaf27bfd.
