### ISSUE TITLE
Page not found: Array Dimensions

### ISSUE THREAD

**Issue by vindarel** [fonol/cl-community-spec#8]
Hello, while browsing the spec this one returned a 404: https://cl-community-spec.github.io/pages/Array-Dimensions.html#Array-Dimensions

CLHS: http://www.lispworks.com/documentation/HyperSpec/Body/f_ar_dim.htm

this one too: https://cl-community-spec.github.io/pages/Array-Rank.html#Array-Rank

this one has no content: https://cl-community-spec.github.io/pages/Multidimensional-Arrays.html#Multidimensional-Arrays

Best,

---

*IDK how to help (I only see a Python script with no dev instructions)*

**Comment by fonol** [comment]
Hi, 
sorry for the late answer. Should all be fixed now. Some of them I had on my list, but simply too little time recently to work on it :(.

**Comment by vindarel** [comment]
Thank you!

(it was a *quick* answer :p )
